name: run_tests
on:
  push:
    paths:
      - 'src/' # Runs only if I modify the source code
      - 'pom.xml' # or change a dependency
    branches:
    - master
  pull_request: 
    branches:
    - master

jobs:
  mvn_test:
    name: Test with Maven
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8,9,10,11] # Supported Java versions
    steps:
    - name: Checkout the latest revision
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Run mvn test
      run: mvn test
